####################
#PseudoUtils Config#
####################

#DO NOT CHANGE THIS LINE! YOUR CONFIG WILL BE RESET UPON LOADING IF THIS LINE IS EDITED!
Version: 1


#########
#Formats#
#########

#Time Format
#Use following codes:
#https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
TimeFormat: "HH:mm:ss"

#Date Format
#Use following codes:
#https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
DateFormat: "yyyy-MM-dd"


#######
#Other#
#######

#How frequently TPS is checked for
#In ticks, how often the plugin will calculate the current TPS
TPSUpdateFrequency: 40