name: PseudoUtils
author: PseudoResonance
main: io.github.pseudoresonance.pseudoutils.PseudoUtils
version: 0.0.7
description: Adds useful utilities
api-version: 1.13
depend: [PseudoAPI]
commands:
  pseudoutils:
    description: PseudoUtils Menu
  metrics:
    description: System metrics
    permission: pseudoutils.metrics
    aliases: [lag,tps]
  brand:
    description: Player client brand
    permission: pseudoutils.brand
  god:
    description: Sets god mode
    permission: pseudoutils.god
  fly:
    description: Sets fly mode
    permission: pseudoutils.fly
permissions:
  pseudoutils.god:
    description: Allows the player to set their god mode
    default: op
  pseudoutils.god.others:
    description: Allows the player to set god mode of other players
    default: op
    children:
      pseudoutils.god: true
  pseudoutils.fly:
    description: Allows the player to set their fly mode
    default: op
  pseudoutils.fly.others:
    description: Allows the player to set fly mode of other players
    default: op
    children:
      pseudoutils.fly: true
  pseudoutils.brand:
    description: Allows the player to see user's client brands
    default: op
  pseudoutils.metrics:
    description: Allows the player to see detailed system metrics
    default: op
    children:
      pseudoutils.metrics.tps: true
  pseudoutils.metrics.other:
    description: Allows the player to see miscellaneous details in system metrics
    default: op
  pseudoutils.metrics.tps:
    description: Allows the player to see tps details in system metrics
    default: op
  pseudoutils.metrics.storage:
    description: Allows the player to see storage details in system metrics
    default: op
  pseudoutils.metrics.java:
    description: Allows the player to see java details in system metrics
    default: op
  pseudoutils.metrics.cpu:
    description: Allows the player to see cpu details in system metrics
    default: op
  pseudoutils.metrics.memory:
    description: Allows the player to see memory details in system metrics
    default: op
  pseudoutils.reset:
    description: Allows the player to reset the config
    default: op
  pseudoutils.reload:
    description: Allows the player to reload the plugin
    default: op
  pseudoutils.*:
    description: Gives the user all PseudoUtils permissions
    default: op
    children:
      pseudoutils.reset: true
      pseudoutils.reload: true
      pseudoutils.brand: true
      pseudoutils.metrics: true
      pseudoutils.metrics.storage: true
      pseudoutils.metrics.java: true
      pseudoutils.metrics.cpu: true
      pseudoutils.metrics.memory: true
      pseudoutils.metrics.other: true
      pseudoutils.god.others: true
      pseudoutils.fly.others: true