name: ${project.artifactId}
author: PseudoResonance
main: io.github.pseudoresonance.pseudoutils.PseudoUtils
version: ${version}
description: Adds useful utilities
api-version: 1.13
depend: [PseudoAPI]
commands:
  pseudoutils:
    description: PseudoUtils Menu
  metrics:
    description: System metrics
    permission: pseudoutils.metrics
    aliases: [lag]
  brand:
    description: Player client brand
    permission: pseudoutils.brand
  god:
    description: Sets god mode
    permission: pseudoutils.god
  fly:
    description: Sets fly mode
    permission: pseudoutils.fly
  heal:
    description: Heals player
    permission: pseudoutils.heal
  back:
    description: Returns player to their last location
    permission: pseudoutils.back
  tp:
    description: Teleports player
    permission: pseudoutils.tp
    aliases: [teleport]
  showitem:
    description: Shows an item in chat
    permission: pseudoutils.showitem
    aliases: [show]
  enchant:
    description: Enchants an item in your hand
    permission: pseudoutils.enchant
    aliases: [ench]
  moonphase:
    description: Shows the current moonphase
    permission: pseudoutils.moonphase
  speed:
    description: Shows a player's fly or walk speed
    permission: pseudoutils.speed
  flyspeed:
    description: Shows a player's fly speed
    permission: pseudoutils.speed
  walkspeed:
    description: Shows a player's walk speed
    permission: pseudoutils.speed
permissions:
  pseudoutils.moonphase:
    description: Allows the player to see the current moon phase
    default: true
  pseudoutils.god:
    description: Allows the player to set their god mode
    default: op
  pseudoutils.god.others:
    description: Allows the player to set god mode of other players
    default: op
    children:
      pseudoutils.god: true
  pseudoutils.fly:
    description: Allows the player to set their fly mode
    default: op
  pseudoutils.fly.others:
    description: Allows the player to set fly mode of other players
    default: op
    children:
      pseudoutils.fly: true
  pseudoutils.enchant:
    description: Allows the player to set enchantments
    default: op
  pseudoutils.enchant.unsafe:
    description: Allows the player to set unsafe enchantments
    default: op
    children:
      pseudoutils.enchant: true
  pseudoutils.heal:
    description: Allows the player to heal themself
    default: op
  pseudoutils.heal.others:
    description: Allows the player to heal other players
    default: op
    children:
      pseudoutils.heal: true
  pseudoutils.showitem:
    description: Allows the player to show an item to a player
    default: true
  pseudoutils.showitem.multiple:
    description: Allows the player to show an item to multiple players at once
    default: op
    children:
      pseudoutils.showitem: true
  pseudoutils.showitem.all:
    description: Allows the player to show an item to all players at once
    default: op
    children:
      pseudoutils.showitem.multiple: true
  pseudoutils.back:
    description: Allows the player to teleport to their last location
    default: true
  pseudoutils.back.others:
    description: Allows the player to teleport other players to their last location
    default: op
    children:
      pseudoutils.back: true
  pseudoutils.back.ondeath:
    description: Allows the player to teleport to their death location
    default: true
    children:
      pseudoutils.back: true
  pseudoutils.tp:
    description: Allows the player to teleport themselves
    default: op
  pseudoutils.tp.coordinates:
    description: Allows the player to teleport to coordinates
    default: op
  pseudoutils.tp.others:
    description: Allows the player to teleport other players
    default: op
    children:
      pseudoutils.tp: true
  pseudoutils.speed:
    description: Allows the player to set their fly or walk speed
    default: op
  pseudoutils.speed.others:
    description: Allows the player to set the fly or walk speed of other players
    default: op
    children:
      pseudoutils.speed: true
  pseudoutils.speed.override:
    description: Allows the player to override the default maximum fly or walk speed
    default: op
    children:
      pseudoutils.speed: true
  pseudoutils.brand:
    description: Allows the player to see user's client brands
    default: op
  pseudoutils.metrics:
    description: Allows the player to see detailed system metrics
    default: true
  pseudoutils.metrics.other:
    description: Allows the player to see miscellaneous details in system metrics
    default: true
  pseudoutils.metrics.tps:
    description: Allows the player to see tps details in system metrics
    default: true
  pseudoutils.metrics.storage:
    description: Allows the player to see storage details in system metrics
    default: op
  pseudoutils.metrics.java:
    description: Allows the player to see java details in system metrics
    default: op
  pseudoutils.metrics.cpu:
    description: Allows the player to see cpu details in system metrics
    default: op
  pseudoutils.metrics.memory:
    description: Allows the player to see memory details in system metrics
    default: op
  pseudoutils.reset:
    description: Allows the player to reset the config
    default: op
  pseudoutils.reload:
    description: Allows the player to reload the plugin
    default: op
  pseudoutils.*:
    description: Gives the user all PseudoUtils permissions
    default: op
    children:
      pseudoutils.reset: true
      pseudoutils.reload: true
      pseudoutils.brand: true
      pseudoutils.metrics: true
      pseudoutils.metrics.tps: true
      pseudoutils.metrics.storage: true
      pseudoutils.metrics.java: true
      pseudoutils.metrics.cpu: true
      pseudoutils.metrics.memory: true
      pseudoutils.metrics.other: true
      pseudoutils.god.others: true
      pseudoutils.fly.others: true
      pseudoutils.heal.others: true
      pseudoutils.back.others: true
      pseudoutils.back.ondeath: true
      pseudoutils.tp.coordinates: true
      pseudoutils.tp.others: true
      pseudoutils.speed.others: true
      pseudoutils.speed.override: true