name: PseudoUtils
author: PseudoResonance
main: io.github.pseudoresonance.pseudoutils.PseudoUtils
version: 0.0.1
description: Adds useful utilities
depend: [PseudoAPI]
commands:
  pseudoutils:
    description: PseudoUtils Menu
  metrics:
    description: System metrics
    permission: pseudoutils.metrics
    aliases: [lag,tps]
  brand:
    description: Player client brand
    permission: pseudoutils.brand
permissions:
  pseudoutils.brand:
    description: Allows the player to see user's client brands
    default: op
  pseudoutils.metrics:
    description: Allows the player to see detailed system metrics
    default: op
    children:
      pseudoutils.metrics.tps: true
  pseudoutils.metrics.other:
    description: Allows the player to see miscellaneous details in system metrics
    default: op
  pseudoutils.metrics.tps:
    description: Allows the player to see tps details in system metrics
    default: op
  pseudoutils.metrics.java:
    description: Allows the player to see java details in system metrics
    default: op
  pseudoutils.metrics.cpu:
    description: Allows the player to see cpu details in system metrics
    default: op
  pseudoutils.metrics.memory:
    description: Allows the player to see memory details in system metrics
    default: op
  pseudoutils.reset:
    description: Allows the player to reset the config
    default: op
  pseudoutils.reload:
    description: Allows the player to reload the plugin
    default: op
  pseudoutils.*:
    description: Gives the user all PseudoUtils permissions
    default: op
    children:
      pseudoutils.reset: true
      pseudoutils.reload: true
      pseudoutils.brand: true
      pseudoutils.metrics: true
      pseudoutils.metrics.java: true
      pseudoutils.metrics.cpu: true
      pseudoutils.metrics.memory: true
      pseudoutils.metrics.other: true